name: Release

on:
  push:
    tags:
      - 'v*' # triggers on any version tag i.e. v1.0.0, v0.2.1, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Package and publish to CurseForge
        uses: BigWigsMods/packager@v2
        with:
          args: -p ${{ secrets.CF_PROJECT_ID }}
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GAME_VERSION: "2.5.5"
